In [3]:
"""
NumPy Array Objcet:

1. NumPy has a multidimensional array object called ndarray. It consists of two parts:
   -- The actual data
   -- Some metadata describing the data
   The majority of array operations leave the raw data untouched. The only aspect that changes is the metadata.

2. The NumPy array is in general homogeneous — the items in the array have to be of the same type. The advantage is that, if we know that
   the items in the array are of the same type, it is easy to determine the storage size required for the array. NumPy arrays are indexed
   starting from 0, just like in Python.

3.  The shape attribute of the array is a tuple, which contains the length in each dimension. A tuple in Python is an immutable
    (it can't change) sequence of values. Once tuples are created, we are not allowed to change the values of tuple elements
    or append new elements. This makes tuples safer than lists because you can't mutate them by accident. A common use case for tuples
    is as return value of functions.

4. The array() function creates an array from an object that you give to it. The object needs to be array-like, for instance, a Python list.
   The object is the only required argument of the array() function. NumPy functions tend to have a lot of optional arguments with predefined
   defaults.
"""
import numpy as np

a = np.arange(5)
print('a: ', a, a.dtype, a.shape)

b = np.array([np.arange(2), np.arange(2)])
print('b: ', b, b.dtype, b.shape)

c = np.array([[1,2],[3,4]])
print('c: ', c[0, 0], c[0, 1], c[1, 0], c[1, 1])

a:  [0 1 2 3 4] int64 (5,)
b:  [[0 1]
 [0 1]] int64 (2, 2)
c:  1 2 3 4


In [4]:
"""
NumPy Numerical Types (1)

1. Python has an integer type, a float type, and a complex type; however, this is not enough for scientific computing and, for this reason,
   NumPy has a lot more data types with varying precision, dependent on memory requirements.

2. In practice, we need even more types with varying precision and, therefore, different memory size of the type. The majority of the NumPy
   numerical types end with a number. This number indicates the number of bits associated with the type. 
   -- bool                       Boolean (True or False) stored as a bit
   -- inti                       Platform integer (normally either int32 or int64)
   -- int8                       Byte (-128 to 127)
   -- int16                      Integer (-32768 to 32767)
   -- int32                      Integer (-2 ** 31 to 2 ** 31 -1)
   -- int64                      Integer (-2 ** 63 to 2 ** 63 -1)
   -- uint8                      Unsigned integer (0 to 255)
   -- uint16                     Unsigned integer (0 to 65535)
   -- uint32                     Unsigned integer (0 to 2 ** 32 - 1)
   -- uint64                     Unsigned integer (0 to 2 ** 64 - 1)
   -- float16                    Half precision float: sign bit, 5 bits exponent, 10 bits mantissa(小数部分)
   -- float32                    Single precision float: sign bit, 8 bits exponent, 23 bits mantissa
   -- float64 or float           Double precision float: sign bit, 11 bits exponent, 52 bits mantissa
   -- complex64                  Complex number, represented by two 32-bit floats (real and imaginary components)
   -- complex128 or complex      Complex number, represented by two 64-bit floats (real and imaginary components)

3. Data type objects are instances of the numpy.dtype class. Once again, arrays have a data type. To be precise, every element in a NumPy
   array has the same data type. The data type object can tell you the size of the data in bytes.
"""
# request information
print(np.finfo(np.float32))

# converstion function
print(np.float64(42))
print(np.int8(4244), np.int8(42.0))
print(np.bool(42), np.bool(0))
print(np.float(True), np.float(False))

# many functions have a data type argument, which is often optional
a = np.arange(7, dtype=np.uint16)
b = np.arange(7, dtype=np.float)
print(a, a.dtype, b, b.dtype)

# not allowed toa complex number into an integer or float; but you can convert a float in to a complex number
print(np.complex(1.0))
# print(np.int(42.0 + 1.j))

# The size in bytes is given by the itemsize attribute of the dtype clas
print(a.dtype, a.dtype.itemsize)

Machine parameters for float32
---------------------------------------------------------------
precision =   6   resolution = 1.0000000e-06
machep =    -23   eps =        1.1920929e-07
negep =     -24   epsneg =     5.9604645e-08
minexp =   -126   tiny =       1.1754944e-38
maxexp =    128   max =        3.4028235e+38
nexp =        8   min =        -max
---------------------------------------------------------------

42.0
-108 42
True False
1.0 0.0
[0 1 2 3 4 5 6] uint16 [0. 1. 2. 3. 4. 5. 6.] float64
(1+0j)
uint16 2


In [5]:
"""
NumPy Numerical Types (2)

1. Character codes are included for backward compatibility with Numeric. Numeric is the predecessor of NumPy. Their use is not recommended,
   but the codes are provided here because they pop up in several places. We should instead use the dtype objects. 
   -- Integer                    i
   -- Unsigned integer           u
   -- Single precision float     f
   -- Double precision float     d
   -- Boolean                    b
   -- Complex                    D
   -- String                     S
   -- Unicode                    U
   -- Void                       V

2. Python classes have functions, which are called methods, if they belong to a class. Some of these methods are special and used to
   create new objects. These specialized methods are called constructors. We have a variety of ways to create data types. A listing of
   all full data type names can be found with the sctypeDict.keys() function.

3. The str attribute of the dtype class gives a string representation of the data type. It starts with a character representing endianness,
   if appropriate, then a character code, followed by a number corresponding to the number of bytes that each array item requires. Endianness,
   here, refers to the way bytes are ordered within a 32- or 64-bit word. In big-endian order, the most significant byte is stored first,
   indicated by >. In little-endian order, the least significant byte is stored first, indicated by <.
"""
# character code example
a = np.arange(7, dtype='f')
b = np.arange(7, dtype='D')
print(a, a.dtype, b, b.dtype)

# The dtype constructors & attributes
print(np.dtype(float))
print(np.dtype('f'))
print(np.dtype('d'))
print(np.dtype('f8')) #  2, 4, and 8 correspond to 16, 32, and 64-bit floats

# A list of fulldata type
print(np.sctypeDict.keys())

# The dtype attributes
t = np.dtype('float64')
print(t.char, t.type, t.str)

[0. 1. 2. 3. 4. 5. 6.] float32 [0.+0.j 1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j] complex128
float64
float32
float64
float64
dict_keys(['?', 0, 'byte', 'b', 1, 'ubyte', 'B', 2, 'short', 'h', 3, 'ushort', 'H', 4, 'i', 5, 'uint', 'I', 6, 'intp', 'p', 7, 'uintp', 'P', 8, 'long', 'l', 'L', 'longlong', 'q', 9, 'ulonglong', 'Q', 10, 'half', 'e', 23, 'f', 11, 'double', 'd', 12, 'longdouble', 'g', 13, 'cfloat', 'F', 14, 'cdouble', 'D', 15, 'clongdouble', 'G', 16, 'O', 17, 'S', 18, 'unicode', 'U', 19, 'void', 'V', 20, 'M', 21, 'm', 22, 'bool8', 'Bool', 'b1', 'float16', 'Float16', 'f2', 'float32', 'Float32', 'f4', 'float64', 'Float64', 'f8', 'float128', 'Float128', 'f16', 'complex64', 'Complex32', 'c8', 'complex128', 'Complex64', 'c16', 'complex256', 'Complex128', 'c32', 'object0', 'Object0', 'bytes0', 'Bytes0', 'str0', 'Str0', 'void0', 'Void0', 'datetime64', 'Datetime64', 'M8', 'timedelta64', 'Timedelta64', 'm8', 'int64', 'uint64', 'Int64', 'UInt64', 'i8', 'u8', 'int32', 'uint32', 'Int32', 'UIn

In [7]:
"""
Create the record

We created a record data type, which is a heterogeneous data type. The record contained a name as a character string, a number as an integer,
and a price represented by a float. 
"""

t = np.dtype([('name', np.str_, 40), ('numitems', np.int32), ('price', np.float32)])
print(t)
itemz = np.array([('Meaning of life DVD', 42, 3.14), ('Butter', 13, 2.72)], dtype=t)
print(itemz)

[('name', '<U40'), ('numitems', '<i4'), ('price', '<f4')]
[('Meaning of life DVD', 42, 3.14) ('Butter', 13, 2.72)]


In [23]:
"""
Slicing and Indexing

1. Slicing of one-dimensional NumPy arrays works just like slicing of Python lists. 

2. The reshape() function changes the shape of an array. We give it a tuple of integers, corresponding to the new shape. If the dimensions
   are not compatible with the data, an exception is thrown.
"""
# slice
a = np.arange(9)
print("a: ", a[3:7], a[:7:2], a[::-1], a[:7:-1])

# reshape
b = np.arange(24).reshape(2,3,4)
print("b: ", b)
print(b.shape, b[0, 0, 0])

# don't care about the first dim, still want the first column & row using :(colon)
print(b[:,0,0])

# An ellipsis (…) replaces multiple colons
print(b[0], b[0, :, :], b[0, ...], sep='\n')

# using steps to slice:
print(b[0, 1, ::2])

# using ellipsis to sloce
print(b[..., 1], b[:,:,1], sep='\n')

# using negative indices
print(b[0,:,-1])
print(b[0,::-1, -1])
print(b[0,::2,-1])

# reverse
print(b[::-1])

a:  [3 4 5 6] [0 2 4 6] [8 7 6 5 4 3 2 1 0] [8]
b:  [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4) 0
[ 0 12]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[4 6]
[[ 1  5  9]
 [13 17 21]]
[[ 1  5  9]
 [13 17 21]]
[ 3  7 11]
[11  7  3]
[ 3 11]
[[[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]


In [27]:
"""
Manipulating Array Shapes

1. The appropriately named function, flatten() does the same as ravel(), but flatten() always allocates new memory whereas ravel()
   might return a view of the array. A view is a way to share an array, but you need to be careful with views because modifying the view
   affects the underlying array, and therefore this impacts other views. An array copy is safer; however, it uses more memory.

2. The resize() method works just like the reshape() function, but modifies the array it operates on. Both reshape and resize change
   the shape of the numpy array; the difference is that using resize will affect the original array while using reshape create a new reshaped
   instance of the array.

3. Function & description
   -- ravel()      This function returns a one-dimensional array with the same data as the input array and doesn't always return a copy
   -- flatten()    This is a method of ndarray, which flattens arrays and always returns a copy of the array
   -- reshape()    This function modifies the shape of an array
   -- resize()     This function changes the shape of an array and adds copies of the input array if necessary
"""

# ravel() & flatten()
print(b, b.ravel(), b.flatten(), sep="\n")

# another way to do the reshape
b.shape = (6, 4)
print(b)

# transpose()
print(b.transpose())

# resize
b.resize((2, 12))
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  4  8 12 16 20]
 [ 1  5  9 13 17 21]
 [ 2  6 10 14 18 22]
 [ 3  7 11 15 19 23]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]


In [42]:
"""
Stacking

1. Arrays can be stacked horizontally, depth wise, or vertically.

2. The axis argument in concatenate is equivalent to axes in a Cartesian coordinate system and corresponds to the array dimensions.

3. Function & description
   -- vstack()           This function stacks arrays vertically
   -- dstack()           This function stacks arrays depth-wise along the third axis
   -- hstack()           This function stacks arrays horizontally
   -- column_stack()     This function stacks one-dimensional arrays as columns to create a two-dimensional array
   -- row_stack()        This function stacks array vertically
   -- concatenate()      This function concatenates a list or a tuple of arrays
"""

a = np.arange(9).reshape(3, 3)
b = a * 2
print('a:', a)
print('b:', b)

# horizontal stacking: form a tuple of the ndarray objects and give it to the hstack() function
c = np.hstack((a, b))
print('c:', c)

# achieve the same with the concatenate() function
d = np.concatenate((a, b), axis=1)
print('d:', d)

# vertical stacking
e = np.vstack((a, b))
print('e:', e)

# achieve the same with the concatenate() function
f = np.concatenate((a, b), axis=0)
print('f:', f)

# depth-wise stacking using dstack() and a tuple stacks a list of arrays along the third axis (depth)
g = np.dstack((a, b))
print('g:', g)

# column stacking
oned = np.arange(2)
twice_oned = 2 * oned
print('column stacking:', oned, twice_oned, np.column_stack((oned, twice_oned)), sep='\n')
print('two dimensional column stacking', np.column_stack((a, b)))
print('compare:', np.column_stack((a, b)) == np.hstack((a, b)))

# row stacking
print('row stacking:', oned, twice_oned, np.row_stack((oned, twice_oned)), sep='\n')
print('two dimensional row stacking', np.row_stack((a, b)))
print('compare:', np.row_stack((a, b)) == np.vstack((a, b)))

a: [[0 1 2]
 [3 4 5]
 [6 7 8]]
b: [[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
c: [[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]
d: [[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]
e: [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
f: [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
g: [[[ 0  0]
  [ 1  2]
  [ 2  4]]

 [[ 3  6]
  [ 4  8]
  [ 5 10]]

 [[ 6 12]
  [ 7 14]
  [ 8 16]]]
column stacking:
[0 1]
[0 2]
[[0 0]
 [1 2]]
two dimensional column stacking [[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]
compare: [[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]
row stacking:
[0 1]
[0 2]
[[0 1]
 [0 2]]
two dimensional row stacking [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
compare: [[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]

In [53]:
"""
Splitting

1. Arrays can be split vertically, horizontally, or depth wise. The functions involved are hsplit(), vsplit(), dsplit(), and split().
   We can either split into arrays of the same shape or indicate the position after which the split should occur.
"""
print('a:', a)

# horizontal spliting: split along the horizontal axis
b = np.hsplit(a, 3)
print('b: ', b)

c = np.split(a, 3, axis=1)
print('c: ', c)

# vertical spliting: split along the vertical axis
d = np.vsplit(a, 3)
print('d: ', d)

e = np.split(a, 3, axis=0)
print('e: ', e)


# depth-wise splitting
f = np.arange(27).reshape(3, 3, 3)
print("f: ", f)

g = np.dsplit(f, 3)
h = np.hsplit(f, 3)
print("g: ", g)
print("h: ", h)

a: [[0 1 2]
 [3 4 5]
 [6 7 8]]
b:  [array([[0],
       [3],
       [6]]), array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]])]
c:  [array([[0],
       [3],
       [6]]), array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]])]
d:  [array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]
e:  [array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]
f:  [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
g:  [array([[[ 0],
        [ 3],
        [ 6]],

       [[ 9],
        [12],
        [15]],

       [[18],
        [21],
        [24]]]), array([[[ 1],
        [ 4],
        [ 7]],

       [[10],
        [13],
        [16]],

       [[19],
        [22],
        [25]]]), array([[[ 2],
        [ 5],
        [ 8]],

       [[11],
        [14],
        [17]],

       [[20],
        [23],
        [26]]])]
h:  [array([[[ 0,  1,  2]],

       [[ 9, 10, 11]],

       [[18, 19, 

In [69]:
"""
Array attributes
"""
b = np.arange(24).reshape(2, 12)
print("b: ", b)

print("b.ndim: ", b.ndim)           # number of dimensions:
print("b.size: ", b.size)           # number of elements
print("b.itemsize: ", b.itemsize)   # number of bytes for each element
print("b.nbytes: ", b.nbytes)       # total number of bytes the array requires

c = b.reshape(6, 4)
print("c: ", c)
print("c.T: ", c.T)                 # transpose()

d = np.array([0, 1, 2, 3])
print('d.ndim: ', d.ndim)
print('d ', d)
print('d.T: ', d.T)

# complex
f = np.array([1.j + 1, 2.j + 3])
print("f: ", f, f.real, f.imag, f.dtype, f.dtype.str)

# The flat attribute returns a numpy.flatiter object. This is the only way to acquire a flatiter.
# The flat iterator enables us to loop through an array as if it is a flat array.
g = np.arange(4).reshape(2,2)
k = g.flat
print("k: ", k)
for item in k:
    print(item)
print("g.flat[2]: ", g.flat[2])
print("g.flat[[1, 3]]: ", g.flat[[1, 3]])

g.flat = 7
print('g: ', g)

g.flat[[1, 3]] = 1
print('g: ', g)

b:  [[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]
b.ndim:  2
b.size:  24
b.itemsize:  8
b.nbytes:  192
c:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
c.T:  [[ 0  4  8 12 16 20]
 [ 1  5  9 13 17 21]
 [ 2  6 10 14 18 22]
 [ 3  7 11 15 19 23]]
d.ndim:  1
d  [0 1 2 3]
d.T:  [0 1 2 3]
f:  [1.+1.j 3.+2.j] [1. 3.] [1. 2.] complex128 <c16
k:  <numpy.flatiter object at 0x55c44ffa6aa0>
0
1
2
3
g.flat[2]:  2
g.flat[[1, 3]]:  [1 3]
g:  [[7 7]
 [7 7]]
g:  [[7 1]
 [7 1]]


In [71]:
# Convert a NumPy array to a Python list
b = np.array([1. + 1.j, 3. + 2.j])
c = b.tolist()
print("c: ", c)

d = b.astype(int)
print('d: ', d)

e = b.astype(complex)
print('e: ', e)

c:  [(1+1j), (3+2j)]
d:  [1 3]
e:  [1.+1.j 3.+2.j]


/data/home/zhangmu/opt/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: ComplexWarning: Casting complex values to real discards the imaginary part
  
